//generated by fenrisulfr tools
package bleach.protocol
{
	public final class Protocol
	{
		public static const SP_Error:int = 1;
		public static const CP_HeartBeat:int = 16777217;
		public static const SP_HeartBeat:int = 16777218;
		public static const CP_Login:int = 33554434;
		public static const SP_Login:int = 33554435;
		public static const CP_BeginBattle:int = 33554436;
		public static const SP_BeginBattle:int = 33554437;
		public static const CP_CheckAccount:int = 33554438;
		public static const SP_CheckAccount:int = 33554439;
		public static const CP_CreatePlayer:int = 33554440;
		public static const SP_CreatePlayer:int = 33554441;
		public static const CP_CreateRoom:int = 33554442;
		public static const SP_CreateRoom:int = 33554443;
		public static const CP_EnterGameCenter:int = 33554444;
		public static const SP_EnterGameCenter:int = 33554445;
		public static const CP_EnterRoom:int = 33554446;
		public static const SP_EnterRoom:int = 33554447;
		public static const CP_ExitBattle:int = 33554448;
		public static const SP_ExitBattle:int = 33554449;
		public static const CP_ExitRoom:int = 33554450;
		public static const SP_ExitRoom:int = 33554451;
		public static const CP_GetRoomList:int = 33554452;
		public static const SP_GetRoomList:int = 33554453;
		public static const CP_Ready:int = 33554454;
		public static const SP_Ready:int = 33554455;
		public static const CP_SelectDefaultHero:int = 33554456;
		public static const SP_SelectDefaultHero:int = 33554457;
		public static const CP_SelectSection:int = 33554458;
		public static const SP_SelectSection:int = 33554459;
		public static const SP_UpdateRoom:int = 33554460;
		public static const CP_UpdateSlot:int = 33554461;
		
	}
}