//generated by fenrisulfr tools
package bleach.module.protocol
{
	public final class Protocol
	{
		public static const CM_HeartBeat:int = 1;
		public static const SM_HeartBeat:int = 2;
		public static const SM_Error:int = 3;
		public static const CM_CheckAccount:int = 101;
		public static const SM_CheckAccount:int = 102;
		public static const CM_CreatePlayer:int = 103;
		public static const SM_CreatePlayer:int = 104;
		public static const CM_Login:int = 105;
		public static const SM_Login:int = 106;
		public static const CM_EnterGameCenter:int = 107;
		public static const SM_EnterGameCenter:int = 108;
		public static const CM_GetRoomList:int = 109;
		public static const SM_GetRoomList:int = 110;
		public static const CM_CreateRoom:int = 111;
		public static const SM_CreateRoom:int = 112;
		public static const CM_SelectSection:int = 113;
		public static const SM_SelectSection:int = 114;
		
	}
}